"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { Apple, Bell, BellRing, BookOpen, CircleDollarSign, ClipboardCheck, Dumbbell, Globe2, HeartPulse, Home, LayoutDashboard, LogOut, Menu, MessageCircle, Plus, Settings, Target, TrendingDown, Trophy, Users, X } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { getNotifications, getViewer, markNotificationsRead } from "@/lib/evolink-data";
import { createClient } from "@/lib/supabase/client";

type Profile = "student" | "professional";
type InstallEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
const navStudent = [["Início","/aluno",Home],["Dieta","/aluno/dieta",Apple],["Treino","/aluno/treino",Dumbbell],["Comunidade","/aluno/comunidade",Globe2],["Cardio","/aluno/cardio",HeartPulse],["Hábitos","/aluno/habitos",Target],["Evolução","/aluno/evolucao",TrendingDown],["Conquistas","/conquistas",Trophy],["Perfil","/aluno/perfil",Settings]] as const;
const navPro = [["Visão geral","/profissional",LayoutDashboard],["Alunos","/profissional/alunos",Users],["Comunidade","/profissional/comunidade",Globe2],["CRM e lembretes","/profissional/crm",BellRing],["Financeiro","/profissional/financeiro",CircleDollarSign],["Dietas","/profissional/dietas",Apple],["Treinos","/profissional/treinos",Dumbbell],["Modelos","/profissional/modelos",BookOpen],["Check-ins","/profissional/check-ins",ClipboardCheck],["Chat","/profissional/chat",MessageCircle],["Biblioteca","/profissional/biblioteca/exercicios",BookOpen],["Configurações","/profissional/configuracoes",Settings]] as const;

function Mark({ small=false}:{small?:boolean}){return <div className={`${small?"h-8 w-8":"h-11 w-11"} relative overflow-hidden rounded-2xl bg-[#07352b] shadow-lg shadow-emerald-900/15`}><Image src="/brand/evolink-mark-192.png" alt="Evolink" fill sizes={small?"32px":"44px"} className="scale-125 object-cover"/></div>}
function Avatar({name, className=""}:{name:string,className?:string}){const letters=name.split(" ").map(x=>x[0]).slice(0,2).join("");return <div className={`grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-[#b8e986] to-[#51aa83] text-xs font-bold text-[#174237] ${className}`}>{letters}</div>}
function Button({children,onClick,kind="primary",className="",disabled=false,type}:{children:React.ReactNode,onClick?:()=>void,kind?:"primary"|"soft"|"outline",className?:string,disabled?:boolean,type?:"button"|"submit"|"reset"}){const reduceMotion=useReducedMotion();const types={primary:"bg-[#087a50] text-white hover:bg-[#066741] shadow-lg shadow-emerald-900/10",soft:"bg-[#e7f4ec] text-[#076841] hover:bg-[#d8ecdf]",outline:"border border-[#dbe7e0] bg-white text-[#285248] hover:bg-[#f7faf8]"};return <motion.button type={type} whileHover={reduceMotion||disabled?undefined:{y:-1}} whileTap={reduceMotion||disabled?undefined:{scale:.975,y:1}} transition={{type:"spring",stiffness:520,damping:28,mass:.45}} disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold transition-colors disabled:opacity-50 ${types[kind]} ${className}`}>{children}</motion.button>}
function InstallPWAButton(){const [event,setEvent]=useState<InstallEvent|null>(null);const reduceMotion=useReducedMotion();useEffect(()=>{const capture=(e:Event)=>{e.preventDefault();setEvent(e as InstallEvent)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture)},[]);if(!event)return null;return <motion.button whileTap={reduceMotion?undefined:{scale:.97,y:1}} onClick={async()=>{await event.prompt();setEvent(null)}} className="fixed bottom-20 right-4 z-40 flex items-center gap-2 rounded-full border border-[#d5e7dc] bg-white/95 px-3.5 py-2.5 text-xs font-bold text-[#087a50] shadow-lg shadow-emerald-950/10 backdrop-blur transition hover:bg-[#f4fbf7] lg:bottom-6 lg:right-6"><Plus size={15}/> Instalar app</motion.button>}

function NotificationButton(){const router=useRouter();const [open,setOpen]=useState(false);const [viewerId,setViewerId]=useState<string|null>(null);const [notes,setNotes]=useState<Awaited<ReturnType<typeof getNotifications>>>([]);const reduceMotion=useReducedMotion();const unread=notes.filter(note=>!note.read_at).length;useEffect(()=>{let active=true;let channel:ReturnType<ReturnType<typeof createClient>["channel"]>|undefined;const supabase=createClient();const refresh=async(id:string)=>{const items=await getNotifications(id);if(active)setNotes(items)};supabase.auth.getUser().then(({data})=>{const id=data.user?.id;if(!active||!id)return;setViewerId(id);void refresh(id);channel=supabase.channel(`notifications:${id}:${crypto.randomUUID()}`).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`recipient_id=eq.${id}`},()=>void refresh(id)).subscribe()});return()=>{active=false;if(channel)void supabase.removeChannel(channel)}},[]);const markAll=async()=>{if(!viewerId)return;await markNotificationsRead(viewerId);setNotes(items=>items.map(item=>({...item,read_at:item.read_at??new Date().toISOString()})))};return <div className="relative"><button aria-label="Notificações" onClick={()=>setOpen(v=>!v)} className="relative grid h-10 w-10 place-items-center rounded-xl text-[#52665e] transition hover:bg-white active:scale-95"><Bell size={20}/>{unread>0&&<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#f19e4c]"/>}</button><AnimatePresence>{open&&<motion.div initial={reduceMotion?false:{opacity:0,y:-6,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={reduceMotion?undefined:{opacity:0,y:-4,scale:.98}} transition={{duration:.18}} className="absolute right-0 top-12 z-50 w-[min(21rem,calc(100vw-2rem))] rounded-2xl border border-[#dbe7e0] bg-white p-4 shadow-xl shadow-emerald-950/10"><div className="flex items-center justify-between"><div><p className="font-bold">Notificações</p><p className="text-xs text-[#71837b]">Atualizações da sua jornada</p></div>{unread>0&&<button onClick={()=>void markAll()} className="text-xs font-bold text-[#087a50]">Marcar como lidas</button>}</div><div className="mt-3 space-y-1">{notes.length===0?<p className="rounded-xl bg-[#f3f8f5] p-3 text-sm text-[#71837b]">Nenhuma atualização por enquanto.</p>:notes.map(note=><button key={note.id} onClick={()=>{void markAll();setOpen(false);if(note.href)router.push(note.href)}} className="flex w-full gap-3 rounded-xl p-3 text-left transition hover:bg-[#f3f8f5]"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${note.read_at?"bg-[#d8e3dd]":"bg-[#48ae82]"}`}/><span><span className="block text-sm font-bold text-[#274c41]">{note.title}</span>{note.body&&<span className="mt-0.5 block text-sm leading-relaxed text-[#456158]">{note.body}</span>}</span></button>)}</div></motion.div>}</AnimatePresence></div>}
function Shell({profile,children}:{profile:Profile,children:React.ReactNode}){
  const router=useRouter(),path=usePathname(); const nav=profile==="student"?navStudent:navPro;
  const [mobileOpen,setMobileOpen]=useState(false);
  const [viewerName,setViewerName]=useState(profile==="student"?"Sua conta":"Conta profissional");
  useEffect(()=>{let active=true;getViewer().then(viewer=>{if(active&&viewer?.role===profile)setViewerName(viewer.fullName)});return()=>{active=false}},[profile]);
  const today=useMemo(()=>new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long"}).format(new Date()),[]);
  async function leave(){window.sessionStorage.removeItem("evolink-demo-role");await createClient().auth.signOut();router.replace("/login");router.refresh()}
  const links=(compact=false)=><nav className={compact?"space-y-1":"mt-3 space-y-1"}>{nav.map(([name,href,Icon])=><button key={href} onClick={()=>{setMobileOpen(false);router.push(href)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${path===href?"bg-[#e7f4ec] text-[#087a50]":"text-[#61756d] hover:bg-[#f4f8f6]"}`}><Icon size={19}/>{name}</button>)}</nav>;
  return <div className="min-h-[100dvh] bg-[#f7faf8]"><InstallPWAButton/><aside className="fixed inset-y-0 left-0 z-20 hidden w-64 border-r border-[#e2ece6] bg-white p-5 lg:block"><button onClick={()=>router.push(profile==="student"?"/aluno":"/profissional")} className="flex items-center gap-3"><Mark small/><span className="text-xl font-black">evolink</span></button><p className="mt-9 px-3 text-[10px] font-bold tracking-[.14em] text-[#91a39b]">{profile==="student"?"SUA JORNADA":"GESTÃO PROFISSIONAL"}</p>{links()}<div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-[#f3f8f5] p-3"><div className="flex items-center gap-2"><Avatar name={viewerName}/><div className="min-w-0 text-left"><p className="truncate text-sm font-bold">{viewerName}</p><p className="text-xs text-[#71837b]">{profile==="student"?"Aluno":"Profissional"}</p></div><button aria-label="Sair" onClick={()=>void leave()} className="ml-auto text-[#71837b]"><LogOut size={16}/></button></div></div></aside><header className="sticky top-0 z-10 flex h-[68px] items-center justify-between border-b border-[#e5eee9] bg-[#f7faf8]/90 px-4 backdrop-blur lg:ml-64 lg:px-8"><div className="flex items-center gap-2 lg:hidden"><Mark small/><b>evolink</b></div><p className="hidden text-sm capitalize text-[#71837b] lg:block">{profile==="student"?today:"Seu painel profissional"}</p><div className="ml-auto flex items-center gap-1.5"><NotificationButton/><button aria-label="Abrir menu" onClick={()=>setMobileOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl text-[#52665e] lg:hidden"><Menu size={20}/></button></div></header>{mobileOpen&&<div className="fixed inset-0 z-50 bg-[#061d19]/35 p-4 lg:hidden" onClick={()=>setMobileOpen(false)}><section className="ml-auto w-full max-w-xs rounded-3xl bg-white p-4 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="flex items-center justify-between"><b>Menu</b><button aria-label="Fechar menu" onClick={()=>setMobileOpen(false)} className="rounded-full bg-[#eef4f0] p-2"><X size={17}/></button></div>{links(true)}<Button kind="outline" onClick={()=>void leave()} className="mt-4 w-full text-[#b94242]"><LogOut size={16}/> Sair</Button></section></div>}<main className="mx-auto max-w-[1440px] px-4 pb-24 pt-5 md:px-8 lg:ml-64 lg:pb-10">{children}</main><nav className="fixed bottom-0 z-30 flex w-full justify-around border-t border-[#e2ece6] bg-white px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 lg:hidden">{nav.slice(0,5).map(([name,href,Icon])=><button key={href} onClick={()=>router.push(href)} className={`flex min-w-14 flex-col items-center gap-1 py-1 text-[10px] font-bold ${path===href?"text-[#087a50]":"text-[#91a39b]"}`}><Icon size={20}/>{name}</button>)}</nav></div>
}

function PageTitle({kicker,title,text}:{kicker:string,title:string,text:string}){return <div className="rise"><p className="text-xs font-bold tracking-[.15em] text-[#087a50]">{kicker}</p><h1 className="mt-1 text-3xl font-bold tracking-tight md:text-4xl">{title}</h1><p className="mt-2 text-sm text-[#71837b]">{text}</p></div>}

export { Shell, PageTitle, Button, Avatar };
