"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, AlertCircle, Apple, BellRing, Check, CheckCircle2, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardCheck, Dumbbell, HeartPulse, Plus, Search, ShieldCheck, Target, UserRound, Weight } from "lucide-react";
import { Avatar, Button, PageTitle, Shell } from "@/components/app-shell";
import { WellnessManager } from "@/components/wellness-manager";
import { ProgressOverview } from "@/components/evolution-page";
import { addStudentNote, createProfessionalInvite, getProfessionalCheckins, getProfessionalOverview, getProfessionalStudentDetail, getProfessionalStudents, getStudentDiet, reviewCheckin, saveCheckin, toggleMeal, type Meal, type Viewer } from "@/lib/evolink-data";

function LoadingCard({ label = "Carregando sua rotina" }: { label?: string }) {
  return <div className="mt-7 animate-pulse rounded-3xl border border-[#e2ece6] bg-white p-6"><div className="h-4 w-32 rounded bg-[#e8f1ed]" /><div className="mt-4 h-8 w-2/3 rounded bg-[#edf4f0]" /><p className="mt-4 text-sm text-[#71837b]">{label}</p></div>;
}

function EmptyCard({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) {
  return <section className="mt-7 rounded-3xl border border-dashed border-[#bfd7c9] bg-white p-7 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#e7f4ec] text-[#087a50]"><Dumbbell size={22} /></div><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-[#71837b]">{text}</p>{action && <div className="mt-5">{action}</div>}</section>;
}

export function LiveDiet({ viewer }: { viewer: Viewer }) {
  const [meals, setMeals] = useState<Meal[] | null>(null); const [done, setDone] = useState<Set<string>>(new Set()); const [saving, setSaving] = useState<string | null>(null);
  useEffect(() => { getStudentDiet(viewer.id).then(result => { setMeals(result.meals); setDone(result.completedMealIds); }); }, [viewer.id]);
  async function toggle(mealId: string) { const completed = !done.has(mealId); setSaving(mealId); const { error } = await toggleMeal(viewer.id, mealId, completed); if (!error) { setDone(previous => { const next = new Set(previous); if (completed) next.add(mealId); else next.delete(mealId); return next; }); } setSaving(null); }
  return <Shell profile="student"><PageTitle kicker="NUTRIÇÃO" title="Sua dieta de hoje" text="Marque cada refeição ao concluir." />{meals === null ? <LoadingCard label="Buscando a dieta publicada para você." /> : meals.length === 0 ? <EmptyCard title="Nenhuma dieta publicada" text="Quando sua profissional publicar o plano, suas refeições aparecerão aqui." /> : <div className="mt-7 grid gap-4 xl:grid-cols-2">{meals.map(meal => <article key={meal.id} className={`rounded-3xl border bg-white p-5 soft-shadow ${done.has(meal.id) ? "border-[#bfe4cd]" : "border-[#e2ece6]"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#087a50]">{meal.scheduled_time?.slice(0, 5) ?? "SEM HORÁRIO"}</p><h2 className="mt-1 text-xl font-bold">{meal.name}</h2></div>{done.has(meal.id) && <span className="grid h-8 w-8 place-items-center rounded-full bg-[#e7f4ec] text-[#087a50]"><Check size={16} /></span>}</div><ul className="mt-5 space-y-2">{meal.meal_items.map(item => <li key={item.id} className="flex gap-2 text-sm text-[#52665e]"><Check size={16} className="mt-0.5 shrink-0 text-[#48ae82]" />{item.description}{item.quantity ? ` - ${item.quantity}${item.unit ?? ""}` : ""}</li>)}</ul>{meal.notes && <p className="mt-4 rounded-xl bg-[#f3f8f5] p-3 text-sm text-[#52665e]">{meal.notes}</p>}<Button disabled={saving === meal.id} onClick={() => toggle(meal.id)} className="mt-6 w-full">{done.has(meal.id) ? "Desmarcar refeição" : "Concluir refeição"}</Button></article>)}</div>}</Shell>;
}

export function LiveCheckin({ viewer }: { viewer: Viewer }) {
  const [nutrition, setNutrition] = useState(4), [trainingDays, setTrainingDays] = useState(3), [energy, setEnergy] = useState(4), [weight, setWeight] = useState(""), [message, setMessage] = useState(""), [sent, setSent] = useState(false), [error, setError] = useState("");
  async function submit() { setError(""); const response = await saveCheckin(viewer, { nutrition, trainingDays, energy, weight: weight ? Number(weight.replace(",", ".")) : undefined, message }); if (response.error) setError(response.error.message); else setSent(true); }
  if (sent) return <Shell profile="student"><PageTitle kicker="CHECK-IN" title="Check-in enviado" text="Sua profissional receberá suas respostas." /><EmptyCard title="Tudo certo por aqui" text="Você pode continuar registrando sua rotina. Sua profissional responderá quando revisar o check-in." /></Shell>;
  return <Shell profile="student"><PageTitle kicker="CHECK-IN SEMANAL" title="Como foi sua semana?" text="Suas respostas ajudam a personalizar o acompanhamento." /><section className="mt-7 max-w-2xl rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><Score label="Alimentação" value={nutrition} onChange={setNutrition} /><Score label="Disposição" value={energy} onChange={setEnergy} /><label className="mt-6 block text-sm font-bold">Dias de treino<input value={trainingDays} onChange={event => setTrainingDays(Number(event.target.value))} min="0" max="7" type="number" className="mt-2 block w-full rounded-xl border border-[#dbe7e0] px-4 py-3 font-normal outline-none focus:border-[#087a50]" /></label><label className="mt-5 block text-sm font-bold">Peso atual (opcional)<input value={weight} onChange={event => setWeight(event.target.value)} inputMode="decimal" placeholder="Ex.: 86,4" className="mt-2 block w-full rounded-xl border border-[#dbe7e0] px-4 py-3 font-normal outline-none focus:border-[#087a50]" /></label><label className="mt-5 block text-sm font-bold">Quer contar algo?<textarea value={message} onChange={event => setMessage(event.target.value)} className="mt-2 min-h-28 w-full rounded-xl border border-[#dbe7e0] p-4 font-normal outline-none focus:border-[#087a50]" placeholder="Dificuldades, dúvidas ou conquistas da semana." /></label>{error && <p className="mt-4 text-sm font-semibold text-[#b94242]">{error}</p>}<Button onClick={submit} className="mt-6 w-full">Enviar check-in<ChevronRight size={17} /></Button></section></Shell>;
}

function Score({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <div className="mt-5"><p className="text-sm font-bold">{label}</p><div className="mt-2 grid grid-cols-5 gap-2">{[1, 2, 3, 4, 5].map(item => <button key={item} onClick={() => onChange(item)} className={`rounded-xl border p-3 text-sm font-bold ${item === value ? "border-[#087a50] bg-[#eff9f3] text-[#087a50]" : "border-[#dbe7e0]"}`}>{item}</button>)}</div></div>; }

export function LiveProfessionalDashboard({ viewer }: { viewer: Viewer }) {
  const [overview, setOverview] = useState<Awaited<ReturnType<typeof getProfessionalOverview>> | null>(null); const [invite, setInvite] = useState(""); const [inviteStatus, setInviteStatus] = useState(""); const router = useRouter();
  useEffect(() => { getProfessionalOverview(viewer.id).then(setOverview); }, [viewer.id]);
  async function createInvite() { setInviteStatus(""); const { data, error } = await createProfessionalInvite(viewer.id); if (error || !data) { setInviteStatus(error?.message ?? "Não foi possível criar o convite."); return; } setInvite(`${window.location.origin}/aluno/perfil?convite=${data.token}`); setInviteStatus("Convite criado. Envie o link ao aluno."); }
  async function copyInvite() { if (!invite) return; try { await navigator.clipboard.writeText(invite); setInviteStatus("Link copiado."); } catch { setInviteStatus("Não foi possível copiar automaticamente. Selecione o link para copiar."); } }
  const inviteAction = <div><Button onClick={createInvite}>Criar convite</Button>{invite && <div className="mt-4 rounded-xl bg-[#f3f8f5] p-3 text-left"><p className="text-xs font-bold text-[#087a50]">LINK PARA O ALUNO</p><p className="mt-1 break-all text-sm text-[#52665e]">{invite}</p><Button kind="outline" className="mt-3 py-2 text-xs" onClick={copyInvite}>Copiar link</Button></div>}{inviteStatus && <p className="mt-3 text-sm font-semibold text-[#087a50]">{inviteStatus}</p>}</div>;
  if (overview === null) return <Shell profile="professional"><PageTitle kicker="VISÃO GERAL" title={`Olá, ${viewer.fullName.split(" ")[0]}.`} text="Carregando o pulso da sua consultoria." /><LoadingCard label="Consolidando alunos, check-ins e financeiro." /></Shell>;
  const activeStudents = overview.students.filter(item => (item.student_profiles as { access_status?: string } | null)?.access_status !== "suspended").length;
  const suspended = overview.students.length - activeStudents;
  return <Shell profile="professional"><PageTitle kicker="VISÃO GERAL" title={`Olá, ${viewer.fullName.split(" ")[0]}.`} text="Aqui está o que precisa da sua atenção hoje." />
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ProMetric label="ALUNOS ATIVOS" value={String(activeStudents)} detail={`${overview.students.length} em acompanhamento`} icon={UserRound} /><ProMetric label="CHECK-INS PENDENTES" value={String(overview.pendingCheckins.length)} detail="Aguardando feedback" icon={ClipboardCheck} warning={overview.pendingCheckins.length > 0} /><ProMetric label="EM ATRASO" value={new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(overview.finance.metrics.overdue)} detail="Mensalidades vencidas" icon={CircleDollarSign} warning={overview.finance.metrics.overdue > 0} /><ProMetric label="ACESSOS SUSPENSOS" value={String(suspended)} detail="Revisar regularizações" icon={ShieldCheck} warning={suspended > 0} /></div>
    {overview.students.length === 0 ? <EmptyCard title="Nenhum aluno ativo" text="Crie um convite e envie o link para o aluno concluir o vínculo." action={inviteAction} /> : <div className="mt-6 grid gap-5 xl:grid-cols-[1.05fr_.95fr]"><section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Precisa de atenção</h2><p className="text-sm text-[#71837b]">Prioridades geradas pelos dados atuais.</p></div>{overview.attention.length > 0 && <span className="rounded-full bg-[#fff1d2] px-2.5 py-1 text-xs font-bold text-[#a97000]">{overview.attention.length} item(ns)</span>}</div>{overview.attention.length === 0 ? <div className="mt-5 rounded-2xl bg-[#f3f8f5] p-5 text-center"><CheckCircle2 className="mx-auto text-[#087a50]" /><p className="mt-2 font-bold">Tudo em dia</p><p className="mt-1 text-sm text-[#71837b]">Nenhuma pendência crítica encontrada.</p></div> : <div className="mt-4 divide-y divide-[#edf2ef]">{overview.attention.map(item => <button key={item.id} onClick={() => item.id.startsWith("checkin-") ? router.push("/profissional/check-ins") : router.push(`/profissional/alunos/${item.studentId}`)} className="flex w-full items-center gap-3 py-3 text-left"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.tone === "danger" ? "bg-[#fdebea] text-[#b94242]" : "bg-[#fff1d2] text-[#a97000]"}`}><AlertCircle size={18} /></span><span><b className="block text-sm">{item.title}</b><span className="text-xs text-[#71837b]">{item.detail}</span></span><ChevronRight size={17} className="ml-auto text-[#91a39b]" /></button>)}</div>}</section>
      <section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Alunos recentes</h2><p className="text-sm text-[#71837b]">Abra a ficha completa em um clique.</p></div><Button kind="soft" className="py-2 text-xs" onClick={() => router.push("/profissional/alunos")}>Ver todos</Button></div><div className="mt-4 space-y-3">{overview.students.slice(0, 5).map(item => <StudentLink key={item.student_id} item={item} onClick={() => router.push(`/profissional/alunos/${item.student_id}`)} />)}</div></section></div>}
    {overview.students.length > 0 && <section className="mt-5 rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><h2 className="font-bold">Convidar aluno</h2><p className="mt-1 text-sm text-[#71837b]">Gere um link individual com validade de 14 dias.</p><div className="mt-4">{inviteAction}</div></section>}
  </Shell>;
}

function ProMetric({ label, value, detail, icon: Icon, warning = false }: { label: string; value: string; detail: string; icon: typeof Activity; warning?: boolean }) { return <section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[.08em] text-[#71837b]">{label}</p><p className="mt-3 text-2xl font-bold tracking-tight">{value}</p></div><span className={`grid h-11 w-11 place-items-center rounded-2xl ${warning ? "bg-[#fff1d2] text-[#a97000]" : "bg-[#e7f4ec] text-[#087a50]"}`}><Icon size={20} /></span></div><p className="mt-4 text-xs font-semibold text-[#61756d]">{detail}</p></section>; }

function StudentLink({ item, onClick }: { item: Awaited<ReturnType<typeof getProfessionalStudents>>[number]; onClick: () => void }) { const profile = item.profiles as { full_name?: string; updated_at?: string } | null; const student = item.student_profiles as { goal?: string | null; access_status?: string } | null; return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-2xl border border-[#edf2ef] p-4 text-left transition hover:-translate-y-0.5 hover:border-[#9fcfb2] hover:shadow-sm active:translate-y-0"><Avatar name={profile?.full_name ?? "Aluno"} /><span className="min-w-0"><b className="block truncate text-sm">{profile?.full_name ?? "Aluno"}</b><span className="block truncate text-xs text-[#71837b]">{student?.goal ?? "Sem objetivo definido"}</span></span><span className={`ml-auto hidden rounded-full px-2.5 py-1 text-[11px] font-bold sm:block ${student?.access_status === "suspended" ? "bg-[#fdebea] text-[#b94242]" : "bg-[#e7f4ec] text-[#087a50]"}`}>{student?.access_status === "suspended" ? "Suspenso" : "Ativo"}</span><ChevronRight size={17} className="text-[#91a39b]" /></button>; }

export function LiveProfessionalStudentsPage({ viewer }: { viewer: Viewer }) {
  const [students, setStudents] = useState<Awaited<ReturnType<typeof getProfessionalStudents>> | null>(null); const [search, setSearch] = useState(""); const router = useRouter();
  useEffect(() => { getProfessionalStudents(viewer.id).then(setStudents); }, [viewer.id]);
  const filtered = (students ?? []).filter(item => { const profile = item.profiles as { full_name?: string } | null; const student = item.student_profiles as { goal?: string | null } | null; const term = search.trim().toLocaleLowerCase("pt-BR"); return !term || `${profile?.full_name ?? ""} ${student?.goal ?? ""}`.toLocaleLowerCase("pt-BR").includes(term); });
  return <Shell profile="professional"><PageTitle kicker="ALUNOS" title="Sua comunidade" text={`${students?.length ?? 0} pessoa(s) em acompanhamento ativo.`} /><label className="mt-6 flex max-w-2xl items-center gap-2 rounded-xl border border-[#dbe7e0] bg-white px-3"><Search size={18} className="text-[#91a39b]" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar por nome ou objetivo" className="w-full py-3.5 text-sm outline-none" /></label>{students === null ? <LoadingCard label="Buscando alunos vinculados." /> : filtered.length === 0 ? <EmptyCard title={search ? "Nenhum aluno encontrado" : "Nenhum aluno ativo"} text={search ? "Tente outro nome ou objetivo." : "Crie um convite na visão geral para iniciar um acompanhamento."} /> : <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item => <StudentLink key={item.student_id} item={item} onClick={() => router.push(`/profissional/alunos/${item.student_id}`)} />)}</div>}</Shell>;
}

export function LiveProfessionalStudentPage({ viewer, studentId }: { viewer: Viewer; studentId: string }) {
  const [detail, setDetail] = useState<Awaited<ReturnType<typeof getProfessionalStudentDetail>>["data"]>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<"summary" | "plans" | "logbook" | "checkins" | "progress" | "notes">("summary"); const [note, setNote] = useState(""); const [privateNote, setPrivateNote] = useState(true); const [savingNote, setSavingNote] = useState(false); const [message, setMessage] = useState(""); const router = useRouter();
  async function load() { const result = await getProfessionalStudentDetail(viewer.id, studentId); setDetail(result.data); setError(result.error?.message ?? ""); setLoading(false); }
  useEffect(() => { let active = true; getProfessionalStudentDetail(viewer.id, studentId).then(result => { if (!active) return; setDetail(result.data); setError(result.error?.message ?? ""); setLoading(false); }); return () => { active = false; }; }, [viewer.id, studentId]);
  async function saveNote() { if (!note.trim()) return; setSavingNote(true); const result = await addStudentNote(viewer.id, studentId, note, privateNote); setSavingNote(false); if (result.error) return setMessage(result.error.message); setNote(""); setMessage("Observação salva no histórico."); await load(); setTab("notes"); }
  if (loading) return <Shell profile="professional"><LoadingCard label="Abrindo a ficha completa do aluno." /></Shell>;
  if (!detail) return <Shell profile="professional"><button onClick={() => router.push("/profissional/alunos")} className="inline-flex items-center gap-2 text-sm font-bold text-[#087a50]"><ChevronLeft size={17} /> Voltar aos alunos</button><EmptyCard title="Não foi possível abrir este aluno" text={error || "Verifique se o vínculo continua ativo."} /></Shell>;
  const profile = detail.profile!; const student = detail.student!; const latestProgress = detail.progress[0]; const payments = (detail.subscription?.subscription_payments ?? []) as { id: string; due_date: string; amount: number; status: string; paid_at: string | null }[]; const latestPayment = [...payments].sort((a, b) => b.due_date.localeCompare(a.due_date))[0];
  const tabs = [["summary", "Resumo"], ["plans", "Planos"], ["logbook", "Logbook"], ["checkins", "Check-ins"], ["progress", "Evolução"], ["notes", "Observações"]] as const;
  return <Shell profile="professional"><button onClick={() => router.push("/profissional/alunos")} className="inline-flex items-center gap-2 text-sm font-bold text-[#087a50]"><ChevronLeft size={17} /> Voltar aos alunos</button><header className="mt-5 flex flex-wrap items-center gap-4 rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><Avatar name={profile.full_name} className="h-16 w-16 text-lg" /><div className="min-w-0 flex-1"><p className="text-xs font-bold tracking-[.12em] text-[#087a50]">FICHA DO ALUNO</p><h1 className="mt-1 truncate text-2xl font-bold md:text-3xl">{profile.full_name}</h1><p className="mt-1 text-sm text-[#71837b]">{student.goal ?? "Objetivo ainda não definido"}</p></div><div className="flex flex-wrap items-center gap-2"><Button kind="outline" className="py-2.5" onClick={() => router.push(`/profissional/crm?aluno=${studentId}`)}><BellRing size={16} /> Criar lembrete</Button><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${student.access_status === "suspended" ? "bg-[#fdebea] text-[#b94242]" : "bg-[#e7f4ec] text-[#087a50]"}`}>{student.access_status === "suspended" ? "Acesso suspenso" : "Acesso ativo"}</span></div></header>
    <nav className="mt-5 flex gap-2 overflow-x-auto rounded-2xl bg-[#eaf2ed] p-1">{tabs.map(([value, label]) => <button key={value} onClick={() => setTab(value)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold ${tab === value ? "bg-white text-[#173f34] shadow-sm" : "text-[#61756d]"}`}>{label}</button>)}</nav>
    {tab === "summary" && <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="grid gap-4 sm:grid-cols-2"><DetailCard icon={Target} label="Objetivo" value={student.goal ?? "Não definido"} detail={student.target_weight_kg ? `Meta: ${String(student.target_weight_kg).replace(".", ",")} kg` : "Sem meta de peso"} /><DetailCard icon={Weight} label="Peso mais recente" value={latestProgress?.weight_kg ? `${String(latestProgress.weight_kg).replace(".", ",")} kg` : "Sem registro"} detail={latestProgress ? new Date(`${latestProgress.recorded_on}T12:00:00`).toLocaleDateString("pt-BR") : "Aguardando evolução"} /><DetailCard icon={ClipboardCheck} label="Check-ins" value={String(detail.checkins.length)} detail={detail.checkins[0]?.status === "submitted" ? "Existe um pendente" : "Histórico atualizado"} /><DetailCard icon={CircleDollarSign} label="Mensalidade" value={latestPayment ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(latestPayment.amount)) : "Não cadastrada"} detail={latestPayment ? (latestPayment.status === "paid" ? "Pagamento confirmado" : `Vence em ${new Date(`${latestPayment.due_date}T12:00:00`).toLocaleDateString("pt-BR")}`) : "Configure no financeiro"} /></div><section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><h2 className="font-bold">Protocolos atuais</h2><div className="mt-4 space-y-3"><ProtocolLine icon={Apple} label="Dieta" title={detail.diet?.title ?? "Nenhuma dieta publicada"} date={detail.diet?.updated_at} /><ProtocolLine icon={Dumbbell} label="Treino" title={detail.workout?.title ?? "Nenhum treino publicado"} date={detail.workout?.updated_at} /><ProtocolLine icon={HeartPulse} label="Cardio" title={detail.cardio?.title ?? "Nenhum cardio publicado"} date={detail.cardio?.updated_at} /></div><Button kind="outline" onClick={() => setTab("plans")} className="mt-4 w-full">Ver planos completos <ChevronRight size={16} /></Button></section></div>}
    {tab === "plans" && <div className="mt-5 grid gap-4 lg:grid-cols-3"><PlanCard icon={Apple} label="DIETA" title={detail.diet?.title ?? "Sem dieta"} lines={[detail.diet ? `${detail.diet.meals?.length ?? 0} refeições` : "Publique o primeiro plano", detail.diet?.status === "published" ? "Publicado" : "Sem publicação"]} action={() => router.push(`/profissional/dietas/nova?aluno=${studentId}`)} actionLabel={detail.diet ? "Atualizar dieta" : "Criar dieta"} /><PlanCard icon={Dumbbell} label="TREINO" title={detail.workout?.title ?? "Sem treino"} lines={[detail.workout ? `${detail.workout.workout_exercises?.length ?? 0} exercícios` : "Publique o primeiro treino", detail.workout?.objective ?? "Sem objetivo específico"]} action={() => router.push(`/profissional/treinos/novo?aluno=${studentId}`)} actionLabel={detail.workout ? "Atualizar treino" : "Criar treino"} /></div>}{tab === "plans" && <WellnessManager professionalId={viewer.id} studentId={studentId} />}
    {tab === "logbook" && <section className="mt-5 rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-bold">Treinos concluídos</h2><p className="mt-1 text-sm text-[#71837b]">Volume, duração e recordes registrados pelo aluno.</p></div><span className="rounded-full bg-[#e7f4ec] px-3 py-1 text-xs font-bold text-[#087a50]">{detail.workoutHistory.length} sessões</span></div>{detail.workoutHistory.length === 0 ? <p className="mt-5 rounded-2xl bg-[#f3f8f5] p-5 text-center text-sm text-[#71837b]">O primeiro treino concluído aparecerá aqui.</p> : <div className="mt-4 space-y-3">{detail.workoutHistory.map(session => { const workout = session.workout_plans as unknown as { title: string } | null; return <article key={session.id} className="grid gap-3 rounded-2xl border border-[#edf2ef] p-4 sm:grid-cols-[1fr_auto_auto_auto]"><div><b className="block text-sm">{workout?.title ?? "Treino"}</b><span className="text-xs text-[#71837b]">{session.completed_at ? new Date(session.completed_at).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "Data não registrada"}</span></div><LogbookMetric label="Tempo" value={`${Math.max(1, Math.round((session.duration_seconds ?? 0) / 60))} min`} /><LogbookMetric label="Volume" value={`${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 0 }).format(Number(session.total_volume_kg))} kg`} /><LogbookMetric label="Recordes" value={String(session.pr_count)} /></article>; })}</div>}</section>}
    {tab === "checkins" && <section className="mt-5 space-y-3">{detail.checkins.length === 0 ? <EmptyCard title="Nenhum check-in enviado" text="O histórico do aluno aparecerá aqui." /> : detail.checkins.map(checkin => <article key={checkin.id} className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#087a50]">SEMANA DE {new Date(`${checkin.week_of}T12:00:00`).toLocaleDateString("pt-BR")}</p><h2 className="mt-1 font-bold">Alimentação {checkin.nutrition_score}/5 · Energia {checkin.energy_score}/5 · {checkin.training_days} treinos</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${checkin.status === "reviewed" ? "bg-[#e7f4ec] text-[#087a50]" : "bg-[#fff1d2] text-[#a97000]"}`}>{checkin.status === "reviewed" ? "Respondido" : "Pendente"}</span></div>{checkin.student_message && <p className="mt-4 rounded-2xl bg-[#f7faf8] p-4 text-sm text-[#52665e]">{checkin.student_message}</p>}{checkin.professional_feedback && <p className="mt-3 text-sm font-semibold text-[#087a50]">Feedback: {checkin.professional_feedback}</p>}</article>)}</section>}
    {tab === "progress" && <ProgressOverview studentId={studentId} target={detail.student?.target_weight_kg ? Number(detail.student.target_weight_kg) : null} />}
    {tab === "notes" && <div className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><h2 className="font-bold">Nova observação</h2><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Registre uma orientação ou informação importante" className="mt-4 min-h-32 w-full rounded-xl border border-[#dbe7e0] p-4 text-sm outline-none focus:border-[#087a50]" /><label className="mt-3 flex items-center gap-2 text-sm text-[#52665e]"><input type="checkbox" checked={privateNote} onChange={event => setPrivateNote(event.target.checked)} className="accent-[#087a50]" /> Nota privada (somente profissional)</label><Button disabled={savingNote || !note.trim()} onClick={saveNote} className="mt-4 w-full"><Plus size={16} /> {savingNote ? "Salvando..." : "Salvar observação"}</Button>{message && <p className="mt-3 text-sm font-semibold text-[#087a50]">{message}</p>}</section><section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><h2 className="font-bold">Histórico de orientações</h2>{detail.notes.length === 0 ? <p className="mt-4 text-sm text-[#71837b]">Nenhuma observação registrada.</p> : <div className="mt-4 space-y-3">{detail.notes.map(item => <article key={item.id} className="rounded-2xl bg-[#f7faf8] p-4"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold text-[#087a50]">{item.is_private ? "PRIVADA" : "COMPARTILHADA"}</span><span className="text-xs text-[#71837b]">{new Date(item.created_at).toLocaleDateString("pt-BR")}</span></div><p className="mt-2 text-sm leading-relaxed text-[#52665e]">{item.body}</p></article>)}</div>}</section></div>}
  </Shell>;
}

function DetailCard({ icon: Icon, label, value, detail }: { icon: typeof Activity; label: string; value: string; detail: string }) { return <section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f4ec] text-[#087a50]"><Icon size={18} /></span><p className="mt-4 text-xs font-bold text-[#71837b]">{label.toUpperCase()}</p><p className="mt-1 text-lg font-bold">{value}</p><p className="mt-2 text-xs text-[#71837b]">{detail}</p></section>; }
function LogbookMetric({ label, value }: { label: string; value: string }) { return <div className="min-w-24 rounded-xl bg-[#f3f8f5] px-3 py-2"><span className="block text-[10px] font-bold text-[#91a39b]">{label.toUpperCase()}</span><b className="text-sm text-[#274c41]">{value}</b></div>; }
function ProtocolLine({ icon: Icon, label, title, date }: { icon: typeof Activity; label: string; title: string; date?: string }) { return <div className="flex items-center gap-3 rounded-2xl bg-[#f7faf8] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f4ec] text-[#087a50]"><Icon size={18} /></span><span className="min-w-0"><span className="text-xs font-bold text-[#087a50]">{label}</span><b className="block truncate text-sm">{title}</b>{date && <span className="text-xs text-[#71837b]">Atualizado em {new Date(date).toLocaleDateString("pt-BR")}</span>}</span></div>; }
function PlanCard({ icon: Icon, label, title, lines, action, actionLabel }: { icon: typeof Activity; label: string; title: string; lines: string[]; action?: () => void; actionLabel?: string }) { return <section className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e7f4ec] text-[#087a50]"><Icon size={20} /></span><p className="mt-5 text-xs font-bold tracking-[.12em] text-[#087a50]">{label}</p><h2 className="mt-1 text-lg font-bold">{title}</h2><div className="mt-4 space-y-2">{lines.map(line => <p key={line} className="flex gap-2 text-sm text-[#61756d]"><Check size={15} className="mt-0.5 shrink-0 text-[#48ae82]" />{line}</p>)}</div>{action && <Button kind="outline" onClick={action} className="mt-5 w-full">{actionLabel} <ChevronRight size={16} /></Button>}</section>; }

export function LiveProfessionalCheckins({ viewer }: { viewer: Viewer }) {
  const [checkins, setCheckins] = useState<Awaited<ReturnType<typeof getProfessionalCheckins>> | null>(null); const [feedback, setFeedback] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  function load() { getProfessionalCheckins(viewer.id).then(setCheckins); }
  useEffect(load, [viewer.id]);
  async function review(id: string) { const { error } = await reviewCheckin(id, feedback[id] ?? ""); setMessage(error ? error.message : "Feedback enviado."); if (!error) load(); }
  return <Shell profile="professional"><PageTitle kicker="CHECK-INS" title="Acompanhamentos semanais" text="Revise as respostas e envie uma orientação objetiva." />{checkins === null ? <LoadingCard label="Buscando check-ins." /> : checkins.length === 0 ? <EmptyCard title="Nenhum check-in enviado" text="Quando um aluno preencher o formulário semanal, ele aparecerá aqui." /> : <div className="mt-7 space-y-4">{checkins.map(checkin => { const profile = checkin.profiles as unknown as { full_name: string } | null; return <section key={checkin.id} className="rounded-3xl border border-[#e2ece6] bg-white p-5 soft-shadow"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{profile?.full_name ?? "Aluno"}</h2><p className="mt-1 text-sm text-[#71837b]">Alimentação {checkin.nutrition_score}/5 · Energia {checkin.energy_score}/5 · {checkin.training_days} dias de treino</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${checkin.status === "reviewed" ? "bg-[#e7f4ec] text-[#087a50]" : "bg-[#fff1d2] text-[#a97000]"}`}>{checkin.status === "reviewed" ? "Respondido" : "Pendente"}</span></div>{checkin.student_message && <p className="mt-4 rounded-2xl bg-[#f7faf8] p-4 text-sm text-[#52665e]">{checkin.student_message}</p>}{checkin.status === "reviewed" ? <p className="mt-4 text-sm font-semibold text-[#087a50]">Seu feedback: {checkin.professional_feedback || "Sem comentário"}</p> : <><textarea value={feedback[checkin.id] ?? ""} onChange={event => setFeedback(value => ({ ...value, [checkin.id]: event.target.value }))} placeholder="Escreva um feedback para o aluno" className="mt-4 min-h-24 w-full rounded-xl border border-[#dbe7e0] p-4 text-sm outline-none focus:border-[#087a50]" /><Button onClick={() => review(checkin.id)} className="mt-3">Enviar feedback</Button></>}</section>; })}</div>}{message && <p className="mt-4 text-sm font-semibold text-[#087a50]">{message}</p>}</Shell>;
}
